__init__.py

The user gets to set a custom delay to wait before the message gets sent. If the user doesn't provide the delay parameter, a default delay of 60 seconds is awaited.

Added delay parameter to 'sendwhatmsg' function.

---

pywhatkit/__init__.py
pywhatkit/mainfunctions.py

steps to use:-
1. enable <less secure app> in your email's privacy setting.
2. call the function with 4 arguments
1. your email id
2. your password
3. receiver's email id
4. message 
note- all arguments must in string

adding sendMail function to send message threw your mail to any other mail

---

pywhatkit/mainfunctions.py

Corrected windows shutdown command

Corrected windows shutdown command

---

pywhatkit/mainfunctions.py

Added cancel shutdown functionality for macos

Added cancel shutdown functionality for macos

---

pywhatkit/mainfunctions.py

Let's say the message is 
msg = """Hi 👋 I am Dipaditya Das.
I am a final year B.Tech. Student 👨‍💻.
I am a Beginner to Open Source Development.🎯"""
Previous the message that was sent was not parsed.
**What I mean is?**
The requested URL will be like 
https://web.whatsapp.com/send?phone=+919999999999&text=Hi 👋 I am Dipaditya Das.
I am a final year B.Tech. Student 👨‍💻.
I am a Beginner to Open Source Development.🎯
Now the browser fails to parse some emojis.
So I have used a library called urllib to parse the message before requesting.
The parsed message will look like
https://web.whatsapp.com/send?phone=+919999999999&text=Hi+%F0%9F%91%8B+I+am+Dipaditya+Das.%0D%0AI+am+a+final+year+B.Tech.+Student+%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB.%0D%0AI+am+a+Beginner+to+Open+Source+Development.%F0%9F%8E%AF

Parsed Message for Multi-Line Message Delivery

---

pywhatkit/mainfunctions.py

Following changes to the file ```mainfunctions.py``` have been made:
- Made the code more readable.
- Added subject support for sending mails.
- Phone number with country code validation with regular expressions.
- Removed unused module bs4.
- Replaced all file writing pieces of code with context manager (```with```).

Minor fixes and improvements

---

pywhatkit/mainfunctions.py

The following changes had been made to `mainfunctions.py` :
- Fixed a Typo in Comments
- Made the Function Description more accurate

FIX: Fixed a small typo in comments

---

requirements.txt

It would make it easier for developers to install the required packages while setting up a development environment.

NEW_FILE: Created requirements.txt

---

CONTRIBUTING.md

The following changes have been made:
- Added CONTRIBUTING.md
It would help everyone to get an overview of how to contribute to the Repository.

NEW_FILE : Created CONTRIBUTING.md

---

CONTRIBUTING.md

The following changes have been made to `CONTRIBUTING.md` :
- Formatted it so that it complies to the Markdown Standards

FIX: Formatted according to Markdown standards

---

pywhatkit/mainfunctions.py

Fixed a typo

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
pywhatkit/__init__.py
pywhatkit/exceptions.py
pywhatkit/history.py

Here is a list of changes:
1. A Pull Request template has been added.
2. Code Formatting Guidelines have been added to the CONTRIBUTING.md file.
3. Removed the `FilePathException` for now because it wasn't being used anywhere in the code base.

Added PR Template and some minor fixes

---

README.md
pywhatkit/__init__.py
pywhatkit/exceptions.py
pywhatkit/mail.py
pywhatkit/wwd.py

Here is a list of changes:
1. The `send_mail` function has been added back.
2. Added a new function `join_discord` so that people can join the discord server directly.
3. Fixed some typos.

send_mail and typos

---

pywhatkit/mail.py

This function will be used for sending an HTML formatted message.
Usage-syntax: 
kit.send_hmail( send_email, sender_pass, subject, html_code , receiver_email)
Usage in two methods:
1) One line [First method]
kit.send_hmail( 'sender@mail.com', 'sender_pass', 'subject', "<h1\>My Heading</h1\><h3\>Topic:</h1\><p\>some message regarding topic</p\>" , 'receiver@gmail.com')
2)Two lines [Second method] 
html_code="""
Your big HTML source code
use inline-style
<\!--this method is best to send HTML mails -->
"""
kit.send_hmail( 'sender@mail.com', 'sender_pass', 'subject', html_code , 'receiver@gmail.com')

Adding send_hmail() function

---

pywhatkit/mail.py

Formatted mail.py to match PEP8

Formatted mail.py

---

pywhatkit/main.py

The following changes were made:
1. Added `open_web()` function to open WhatsApp Web
2. Formatted file

Added a new function

---

pywhatkit/ascii_art.py
pywhatkit/mail.py
pywhatkit/sc.py

Formatted Code

---

requirements.txt

The following changes have been made:
1. A mistakenly added package to the `requirements.txt` has been removed that is known to cause conflicts.

Changes to requirements.txt

---

pywhatkit/main.py

Updated the API's URL to point to new one

Update API URL

---

pywhatkit/sc.py

Changed few lines in which I got bugs and made 'def cancel_shutdown():' independent from 'def shutdown():'

Updated the file with latest bug fixtures

---

CONTRIBUTING.md
LICENSE
pywhatkit/ascii_art.py
pywhatkit/chr_to_handwriting.py
pywhatkit/exceptions.py
pywhatkit/help.py
pywhatkit/history.py
pywhatkit/mail.py
pywhatkit/main.py
pywhatkit/sc.py
pywhatkit/wwd.py
setup.py

The following changes have been made:
1. Fixed some improper type hint issues 
2. Some formatting
3. Removed the `browser` parameter from the `sendwhatmsg` and `sendwhatmsg_instantly` function
4. Removed the `InvalidBrowserName` exception
5. Updated the `CONTRIBUTING.md`
Fixes #49

Type Hint Fixes and Updated Guidelines

---

pywhatkit/main.py
setup.py

The download URL has been updated

Updated Download URL

---

.gitattributes
.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
README.md
pywhatkit/__init__.py
pywhatkit/chr_to_handwriting.py
pywhatkit/main.py
pywhatkit/sc.py
setup.py

1. Added the ability to send images using the `sendwhats_image` function

Added the ability to send images

---

pywhatkit/main.py
pywhatkit/sc.py

The following changes have been made:
1. The Image View window of the `take_screenshot` function now has the title of the file name.
2. Removed some useless variables.

Minor Optimisations

---

README.md
pywhatkit/main.py

- Removed redundant brackets
- Updated Badge styles for the README.md

Updated Badge Style

---

pywhatkit/main.py

The conversion should be from `RGB` to `RGB` not `RBG` to `RBG`

RGB to RGB Error Fix

---

pywhatkit/__init__.py

Added send message to group instantly to __init__.py

Added send message to group instantly to __init__.py

---

README.md

- *Give the PR an appropriate Title.*
- *If you want to fix a lot of Issues together, please consider opening a Draft PR first and mention alL the issues in a list along with the status of the fix that you are working on.*
- *Mention the `IssueNumber` in your PR if it is fixing an Issue with `closes #IssueNumber`.*
- *Please provide sufficient information regarding the changes you have made.*
- *Please read the [CONTRIBUTION](https://github.com/Ankit404butfound/PyWhatKit/blob/master/CONTRIBUTING.md) guidelines first otherwise your PR may not get merged.*
[comment]: <> (Please remove all the above points and this message while creating the PR.)

Fix module name mistake in Readme

---

pywhatkit/whats.py

Added the same functionality for images to be sent at a certain time similar to how text messages can be sent at any time. The algorithm used is the exact same as the one for text messages.

Added sending images at certain time, not just instant.

---

pywhatkit/core/exceptions.py
pywhatkit/whats.py

- closes #178 
- **Changes:**
- Created `InvalidPhoneNumber` Exception.
- Cleaned phone number by removing spaces.
- Raised `InvalidPhoneNumber` Exception when phone number did not satisfy regular expression.

Check complete phone number instead of just country code

---

pywhatkit/__init__.py
pywhatkit/core/core.py

- replaced `web_screenshot` with `take_screenshot` in the `__init__.py` file.
- stored `system().lower()` in a variable `_system` because repeated `.lower()` function is costly.

Important fix and small improvement

---

pywhatkit/core/core.py
pywhatkit/whats.py

fixes #195 

---

README.md

⚠ IMPORTANT POINTS: ⚠
Give the PR an appropriate Title.
If you want to fix a lot of Issues together, please consider opening a Draft PR first and mention alL the issues in a list along with the status of the fix that you are working on.
Mention the IssueNumber in your PR if it is fixing an Issue with closes #IssueNumber.
Please provide sufficient information regarding the changes you have made.
Please read the [CONTRIBUTION](https://github.com/Ankit404butfound/PyWhatKit/blob/master/CONTRIBUTING.md) guidelines first otherwise your PR may not get merged.

I have added the way to create ascii art with pywhatkit in the Usage section

---

pywhatkit/core/core.py
pywhatkit/whats.py

Send multiple messages to the same number.
Issue #124
In this pull request, I added a new function to send multiple messages to a single number (Issue #124). The changes were made in the **whats.py** file, specifically in the **sendwhatmsg** function. Now, the _message argument can be either a list or a string_. Before sending, a check is performed using isinstance(message, list) to determine if the argument is a list. If the result is true, the new **send_message_list** function located in **core.py** is called.
Here is the result
_I appreciate the opportunity to contribute to this project and I hope this new function will be useful to the users of the library._

Send multiple message from a list
